version: '3.8'

services:
  signal:
    image: ghcr.io/m4litt/nkc-signaling
    container_name: nkc-signal
    ports:
      - "4356:4356"
  
  database:
    cap_add: [ SYS_NICE ]
    image: mysql:8.0.35-debian
    container_name: nkc-db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ./database/dumps:/docker-entrypoint-initdb.d
    secrets:
      - db_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  
  back:
    image: ghcr.io/m4litt/nkc-back
    container_name: nkc-back
    environment:
      DB_NAME: nankuruchat
      DB_HOST: nkc-db
      DB_USER: root
      DB_PWD: /run/secrets/db_password
      JWT_SECRET: /run/secrets/jwt_secret
    depends_on:
      database:
        condition: service_healthy
    secrets:
      - db_password
      - jwt_secret
    ports:
      - "12471:12471"

  front:
    image: ghcr.io/ianpolettilucero/nkc-front
    container_name: nkc-front
    depends_on:
      - back
      - signal
    ports:
      - "80:80"

secrets:
  db_password:
    file: secrets/db_password.txt
  jwt_secret:
    file: secrets/jwt_secret.txt
