name: Docker Image CI

on:
  push:
    branches: [ "WRTC-stable" ]
  pull_request:
    branches: [ "WRTC-stable" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:      
    
    - uses: actions/checkout@v3
    
    - name: Build project
      run: npm install; npm run build
    
    - name: Pull SSL certs from Github secrets    
      run:
        echo "${{ secrets.SSL_KEY }}" | base64 --decode > key.pem
        echo "${{ secrets.SSL_CERT }}" | base64 --decode > cert.pem
    
    - name: Build the Docker image
      run: 
        docker build . --file Dockerfile --tag nkc-signaling:stable.latest
        docker push ghcr.io/M4litt/hello-docker-gcr-demo:latest
